### ISSUE TITLE
tf2pickup mumble bot forces CELT codec on the server

### ISSUE THREAD

**Issue by carlocastoldi** [tf2pickup-pl/server#2392]
From what I saw the tf2pickup bot do not support OPUS codec, forcing the server to adopt the very old CELT codec instead if the bot is connected if `opusthreshold>0`.

This problem is even bigger from Mumble client v1.5, as they decided to [drop support for CELT](https://github.com/mumble-voip/mumble/issues/6056#issuecomment-1424565579). This means that if the server is using CELT codec, a player with mumble>=1.5 would not be able to connect to the server with tf2pickup bot in it.

P.S. don't know if this is the proper repository where to report this bug, but i guess it was the better one due to https://github.com/tf2pickup-org/server/pull/1602 PR

**Comment by suprovsky** [comment]
Hey, it's a funny coincidence, beacuse I'm editing our docs right now. Do not use phlak/mumble image; instead use mumblevoip/mumble-server:latest.
phlak/mumble isn't maintained and updated anymore. We have switched onto the official image already.

This place isn't for reporting problems like these - here you can report bugs related with the pickup site strictly. We encourage you to contact us in topics like this on our [Discord](https://discord.tf2pickup.org).

**Comment by carlocastoldi** [comment]
the link to discord is broken

**Comment by suprovsky** [comment]
https://discord.gg/SXtcadpQTK use this one until I fix the right one

**Comment by garrappachc** [comment]
I'm reopening this issue since the mumble bot should use the OPUS codec (even though it doesn't use voice at all).
